// design/scripts/build-index.ts
// Rebuilds tokens/index.json from the individual token files so the aggregator
// is always in sync. The aggregator itself is intentionally thin (just
// references + version); downstream code reads the individual files directly.
//
// Usage: pnpm --filter @eger/design tokens:build

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOKENS_DIR = join(__dirname, "..", "tokens");

const files = readdirSync(TOKENS_DIR)
  .filter((f) => f.endsWith(".json") && f !== "schema.json" && f !== "index.json")
  .sort();

type Token = { value: unknown };
type Group = { [key: string]: Token | Group | unknown };

function isToken(v: unknown): v is Token {
  return !!v && typeof v === "object" && "value" in (v as object);
}

function collectGroups(data: Group, prefix = ""): string[] {
  const out: string[] = [];
  for (const [k, v] of Object.entries(data)) {
    if (k.startsWith("$")) continue;
    const path = prefix ? `${prefix}.${k}` : k;
    if (isToken(v)) {
      out.push(path);
    } else if (v && typeof v === "object") {
      out.push(...collectGroups(v as Group, path));
    }
  }
  return out;
}

let totalTokens = 0;
const summary: Record<string, number> = {};
for (const file of files) {
  const data = JSON.parse(readFileSync(join(TOKENS_DIR, file), "utf8")) as Group;
  const paths = collectGroups(data);
  summary[file] = paths.length;
  totalTokens += paths.length;
}

const index = {
  $schema: "./schema.json",
  $description:
    "Aggregator — regenerated by design/scripts/build-index.ts. Do not edit by hand.",
  color: "see ./colors.json",
  typography: "see ./typography.json",
  spacing: "see ./spacing.json",
  radius: "see ./radius.json",
  shadow: "see ./shadows.json",
  ease: "see ./motion.json#ease",
  duration: "see ./motion.json#duration",
  keyframes: "see ./motion.json#keyframes",
  version: "0.1.0",
  tokenCount: totalTokens,
  sourceFiles: files,
  tokenCountsByFile: summary,
  generatedAt: new Date().toISOString(),
};

writeFileSync(
  join(TOKENS_DIR, "index.json"),
  JSON.stringify(index, null, 2) + "\n",
);
console.log(`✓ Wrote index.json — ${totalTokens} tokens across ${files.length} files.`);